### ISSUE TITLE
Changing ts file instead of html

### ISSUE THREAD

**Issue by ElodieC** [ionic-team/v4-migration-tslint#48] opened 2018-08-21 12:07 UTC
I've got a `home.page.ts` with this content :

```
import { Component, ViewChild } from '@angular/core';
import { Content } from '@ionic/angular';

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  @ViewChild(Content) public content: Content;
}
```

And a `home.page.html` with this :
```
<ion-header>
  <ion-toolbar>
    <ion-buttons start>
      <button ion-button>Text</button>
    </ion-buttons>
    <ion-title>Texte</ion-title>
    <button ion-button menuToggle end>
      <ion-icon name="menu"></ion-icon>
    </button>
  </ion-toolbar>
</ion-header>


<ion-content>
  <p> Blabla </p>

</ion-content>
```

When I run `tslint -c ionic-migration.json -p tsconfig.json --fix`, it modifies home.page.ts replacing `@angular/core` by `@angularslot="secondary"` in first line and doesn't modify anything in home.page.html.

Here is the console output :
`src/app/home/home.page.ts[1, 47]: The start attribute of ion-buttons has been renamed. Use slot="secondary" instead.`

**Comment by dwieeb** [comment] 2018-08-21 18:47
This looks like the same issue as https://github.com/ionic-team/v4-migration-tslint/issues/46

**Comment by dwieeb** [comment] 2018-09-03 17:44
Duplicate of https://github.com/ionic-team/v4-migration-tslint/issues/46

**Closed by dwieeb** 2018-09-03 17:44 UTC
